# Spring properties
spring:
  application:
     name: restaurants-microservice
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

# HTTP Server
server:
  port: 3002 # HTTP (Tomcat) port